/**
 * Aware — Mock Data
 *
 * Realistic product and store data used throughout the frontend skeleton.
 * When backend + Open Food Facts API arrives, this module is replaced
 * by real API calls — all screens already consume the same interfaces.
 */
import { Product, Store, ShoppingList, UserPreferences } from './types';

// ─── Stores ───────────────────────────────────────────────────────────────────
export const STORES: Store[] = [
  {
    id: 'whole_foods',
    name: 'Whole Foods',
    emoji: '🌿',
    color: '#00674B',
    productCount: '11,500+',
    distance: '0.8 mi',
    isOpen: true,
    categories: ['snacks', 'dairy_alternatives', 'produce', 'supplements'],
  },
  {
    id: 'target',
    name: 'Target',
    emoji: '🎯',
    color: '#CC0000',
    productCount: '8,200+',
    distance: '1.2 mi',
    isOpen: true,
    categories: ['snacks', 'beverages', 'frozen', 'condiments'],
  },
  {
    id: 'trader_joes',
    name: "Trader Joe's",
    emoji: '🛒',
    color: '#B8282C',
    productCount: '4,000+',
    distance: '1.5 mi',
    isOpen: true,
    categories: ['snacks', 'dairy_alternatives', 'frozen', 'sauces'],
  },
  {
    id: 'kroger',
    name: 'Kroger',
    emoji: '🏪',
    color: '#004080',
    productCount: '15,000+',
    distance: '2.1 mi',
    isOpen: true,
    categories: ['snacks', 'beverages', 'meat', 'produce'],
  },
  {
    id: 'costco',
    name: 'Costco',
    emoji: '📦',
    color: '#005DAA',
    productCount: '3,800+',
    distance: '3.4 mi',
    isOpen: true,
    categories: ['snacks', 'supplements', 'frozen', 'oils'],
  },
  {
    id: 'walmart',
    name: 'Walmart',
    emoji: '⭐',
    color: '#0071CE',
    productCount: '22,000+',
    distance: '2.8 mi',
    isOpen: true,
    categories: ['snacks', 'beverages', 'condiments', 'frozen'],
  },
  {
    id: 'publix',
    name: 'Publix',
    emoji: '🟢',
    color: '#16883B',
    productCount: '12,000+',
    distance: '3.9 mi',
    isOpen: false,
    categories: ['snacks', 'dairy', 'produce', 'meat'],
  },
  {
    id: 'safeway',
    name: 'Safeway',
    emoji: '🛍️',
    color: '#D22630',
    productCount: '10,500+',
    distance: '4.2 mi',
    isOpen: true,
    categories: ['snacks', 'beverages', 'frozen', 'produce'],
  },
  {
    id: 'sprouts',
    name: 'Sprouts',
    emoji: '🌱',
    color: '#5B8C22',
    productCount: '6,500+',
    distance: '5.0 mi',
    isOpen: true,
    categories: ['supplements', 'dairy_alternatives', 'produce', 'snacks'],
  },
  {
    id: 'heb',
    name: 'H-E-B',
    emoji: '🧡',
    color: '#E31837',
    productCount: '17,000+',
    distance: '5.5 mi',
    isOpen: true,
    categories: ['produce', 'meat', 'dairy', 'snacks'],
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const PRODUCTS: Product[] = [
  {
    id: 'hu_dark_chocolate',
    name: 'Simple Dark Chocolate Bar',
    brand: 'Hu',
    category: 'chocolate',
    emoji: '🍫',
    cleanScore: 94,
    healthScore: 88,
    valueScore: 72,
    badges: ['cleanest', 'best_for_you'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['pcos', 'hypothyroidism', 'diabetes_t2', 'high_cholesterol'],
    allergensPresent: [],
    dietCompatible: ['vegan', 'paleo', 'keto', 'gluten_free', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Organic Cacao', isClean: true, isConcern: false },
      { name: 'Organic Coconut Sugar', isClean: true, isConcern: false },
      { name: 'Organic Cacao Butter', isClean: true, isConcern: false },
    ],
    servingSize: '1 bar (40g)',
    calories: 200,
    protein: 3,
    carbs: 20,
    fat: 14,
    sugar: 9,
    sodium: 10,
    fiber: 4,
    whyClean: 'Only 3 organic ingredients. No refined sugar, no lecithin, no artificial anything. Cacao is a rich source of antioxidants and magnesium.',
    whyGoodForCondition: {
      pcos: 'High magnesium supports hormone balance. Minimal sugar prevents insulin spikes.',
      hypothyroidism: 'Rich in selenium and antioxidants. Low sugar reduces inflammation.',
      diabetes_t2: 'Low glycemic. Antioxidants improve insulin sensitivity.',
    },
    price: '$3.99',
    stores: ['whole_foods', 'target', 'sprouts'],
    verified: true,
  },
  {
    id: 'kite_hill_yogurt',
    name: 'Plain Unsweetened Almond Yogurt',
    brand: 'Kite Hill',
    category: 'dairy_alternatives',
    emoji: '🥛',
    cleanScore: 88,
    healthScore: 92,
    valueScore: 68,
    badges: ['best_for_you', 'best_overall'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['pcos', 'ibs', 'celiac', 'hypothyroidism'],
    allergensPresent: ['tree_nuts'],
    dietCompatible: ['vegan', 'gluten_free', 'dairy_free', 'keto', 'paleo'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Almond Milk', isClean: true, isConcern: false },
      { name: 'Almond Cream', isClean: true, isConcern: false },
      { name: 'Live Active Cultures', isClean: true, isConcern: false },
    ],
    servingSize: '3/4 cup (170g)',
    calories: 110,
    protein: 5,
    carbs: 7,
    fat: 7,
    sugar: 3,
    sodium: 10,
    fiber: 1,
    whyClean: 'Minimal ingredient list. Just almond milk, almond cream, and live cultures. Zero gums, starches, or stabilizers.',
    price: '$6.49',
    stores: ['whole_foods', 'sprouts', 'target'],
    verified: true,
  },
  {
    id: 'simple_mills_crackers',
    name: 'Almond Flour Crackers, Sea Salt',
    brand: 'Simple Mills',
    category: 'chips_crackers',
    emoji: '🍘',
    cleanScore: 85,
    healthScore: 82,
    valueScore: 74,
    badges: ['best_overall'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['celiac', 'diabetes_t2', 'ibs'],
    allergensPresent: ['tree_nuts'],
    dietCompatible: ['gluten_free', 'paleo', 'vegan'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Almond Flour', isClean: true, isConcern: false },
      { name: 'Arrowroot', isClean: true, isConcern: false },
      { name: 'Sunflower Seeds', isClean: true, isConcern: false },
      { name: 'Flaxseeds', isClean: true, isConcern: false },
      { name: 'Sea Salt', isClean: true, isConcern: false },
      { name: 'Rosemary Extract', isClean: true, isConcern: false },
    ],
    servingSize: '17 crackers (30g)',
    calories: 150,
    protein: 3,
    carbs: 17,
    fat: 8,
    sugar: 1,
    sodium: 135,
    fiber: 1,
    whyClean: 'Whole food grain-free ingredients. No canola oil, no soy, no gums. Rosemary extract is a natural preservative.',
    price: '$6.29',
    stores: ['whole_foods', 'target', 'kroger', 'safeway'],
    verified: true,
  },
  {
    id: 'siete_chips',
    name: 'Sea Salt Grain-Free Tortilla Chips',
    brand: 'Siete',
    category: 'chips_crackers',
    emoji: '🌮',
    cleanScore: 82,
    healthScore: 79,
    valueScore: 70,
    badges: ['best_value'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['celiac', 'ibs', 'pcos'],
    allergensPresent: ['tree_nuts'],
    dietCompatible: ['vegan', 'gluten_free', 'paleo', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Cassava Flour', isClean: true, isConcern: false },
      { name: 'Avocado Oil', isClean: true, isConcern: false },
      { name: 'Sea Salt', isClean: true, isConcern: false },
    ],
    servingSize: '1 oz (28g)',
    calories: 130,
    protein: 1,
    carbs: 19,
    fat: 6,
    sugar: 0,
    sodium: 135,
    fiber: 0,
    whyClean: 'Three ingredients. Cassava flour is a resistant starch. Avocado oil is a clean cooking fat with a high smoke point.',
    price: '$4.99',
    stores: ['whole_foods', 'target', 'sprouts', 'kroger'],
    verified: true,
  },
  {
    id: 'rxbar',
    name: 'Chocolate Sea Salt Protein Bar',
    brand: 'RXBAR',
    category: 'bars',
    emoji: '🍫',
    cleanScore: 78,
    healthScore: 83,
    valueScore: 77,
    badges: ['best_for_you'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['diabetes_t2', 'pcos', 'high_cholesterol'],
    allergensPresent: ['eggs', 'tree_nuts'],
    dietCompatible: ['gluten_free', 'dairy_free', 'paleo'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Dates', isClean: true, isConcern: false },
      { name: 'Egg Whites', isClean: true, isConcern: false },
      { name: 'Almonds', isClean: true, isConcern: false },
      { name: 'Cashews', isClean: true, isConcern: false },
      { name: 'Chocolate', isClean: true, isConcern: false },
      { name: 'Sea Salt', isClean: true, isConcern: false },
    ],
    servingSize: '1 bar (52g)',
    calories: 210,
    protein: 12,
    carbs: 23,
    fat: 9,
    sugar: 15,
    sodium: 270,
    fiber: 5,
    whyClean: 'No added sugars — only whole food dates for sweetness. 12g protein from egg whites. No gums, no artificial ingredients.',
    price: '$2.99',
    stores: ['target', 'kroger', 'walmart', 'costco'],
    verified: true,
  },
  {
    id: 'ripple_milk',
    name: 'Original Pea Protein Milk',
    brand: 'Ripple',
    category: 'dairy_alternatives',
    emoji: '🥛',
    cleanScore: 80,
    healthScore: 87,
    valueScore: 76,
    badges: ['best_overall'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['pcos', 'hypothyroidism', 'osteoporosis'],
    allergensPresent: [],
    dietCompatible: ['vegan', 'gluten_free', 'dairy_free', 'nut_free' as any],
    ingredientConcerns: ['sunflower_oil'],
    allIngredients: [
      { name: 'Pea Protein', isClean: true, isConcern: false },
      { name: 'Sunflower Oil', isClean: false, isConcern: true, reason: 'Refined seed oil, high in omega-6' },
      { name: 'Algal Oil', isClean: true, isConcern: false },
      { name: 'Calcium Carbonate', isClean: true, isConcern: false },
      { name: 'Vitamin D2', isClean: true, isConcern: false },
    ],
    servingSize: '1 cup (240ml)',
    calories: 100,
    protein: 8,
    carbs: 6,
    fat: 4.5,
    sugar: 5,
    sodium: 140,
    fiber: 0,
    whyClean: '8g plant protein, nut-free, no carrageenan. One concern: sunflower oil (refined). Otherwise very clean for a plant milk.',
    price: '$4.99',
    stores: ['whole_foods', 'target', 'kroger'],
    verified: true,
  },
  {
    id: 'chosen_avocado_oil',
    name: 'Pure Avocado Oil',
    brand: 'Chosen Foods',
    category: 'oils',
    emoji: '🥑',
    cleanScore: 96,
    healthScore: 94,
    valueScore: 71,
    badges: ['cleanest', 'best_overall'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['heart_disease', 'high_cholesterol', 'pcos', 'diabetes_t2'],
    allergensPresent: [],
    dietCompatible: ['vegan', 'keto', 'paleo', 'whole30', 'gluten_free', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Avocado Oil', isClean: true, isConcern: false },
    ],
    servingSize: '1 tbsp (14g)',
    calories: 120,
    protein: 0,
    fat: 14,
    carbs: 0,
    sugar: 0,
    sodium: 0,
    whyClean: 'Single ingredient. High in oleic acid (heart-healthy omega-9). High smoke point (500°F) — safe for cooking. Minimally refined.',
    price: '$9.99',
    stores: ['whole_foods', 'target', 'costco', 'kroger'],
    verified: true,
  },
  {
    id: 'vital_farms_butter',
    name: 'Pasture-Raised Butter',
    brand: 'Vital Farms',
    category: 'dairy',
    emoji: '🧈',
    cleanScore: 90,
    healthScore: 85,
    valueScore: 69,
    badges: ['cleanest', 'best_for_you'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['hypothyroidism', 'adhd', 'pcos'],
    allergensPresent: ['dairy'],
    dietCompatible: ['keto', 'paleo', 'vegetarian', 'gluten_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Pasture-Raised Cream', isClean: true, isConcern: false },
      { name: 'Salt', isClean: true, isConcern: false },
    ],
    servingSize: '1 tbsp (14g)',
    calories: 100,
    protein: 0,
    fat: 11,
    carbs: 0,
    sugar: 0,
    sodium: 90,
    whyClean: 'Pasture-raised cows produce butter with 5× more CLA and higher omega-3s. Two ingredients only. Ethical sourcing.',
    price: '$7.99',
    stores: ['whole_foods', 'target', 'kroger', 'publix'],
    verified: true,
  },
  {
    id: 'banza_pasta',
    name: 'Chickpea Rotini',
    brand: 'Banza',
    category: 'pasta',
    emoji: '🍝',
    cleanScore: 83,
    healthScore: 88,
    valueScore: 78,
    badges: ['best_for_you', 'best_value'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['diabetes_t2', 'pcos', 'celiac', 'ibs'],
    allergensPresent: [],
    dietCompatible: ['vegan', 'gluten_free', 'vegetarian', 'high_protein' as any],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Chickpea Flour', isClean: true, isConcern: false },
      { name: 'Tapioca', isClean: true, isConcern: false },
      { name: 'Pea Protein', isClean: true, isConcern: false },
      { name: 'Xanthan Gum', isClean: false, isConcern: true, reason: 'Some people with IBS react to xanthan gum' },
    ],
    servingSize: '2 oz dry (57g)',
    calories: 190,
    protein: 11,
    carbs: 32,
    fat: 3,
    sugar: 3,
    sodium: 45,
    fiber: 5,
    whyClean: '11g protein and 5g fiber vs 7g/2g in wheat pasta. Low glycemic. Gluten-free. One note: contains xanthan gum (minor concern for IBS).',
    price: '$3.49',
    stores: ['whole_foods', 'target', 'kroger', 'walmart'],
    verified: true,
  },
  {
    id: 'primal_kitchen_mayo',
    name: 'Avocado Oil Mayo',
    brand: 'Primal Kitchen',
    category: 'condiments',
    emoji: '🫙',
    cleanScore: 87,
    healthScore: 84,
    valueScore: 65,
    badges: ['cleanest'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['heart_disease', 'pcos', 'diabetes_t2'],
    allergensPresent: ['eggs'],
    dietCompatible: ['keto', 'paleo', 'whole30', 'gluten_free', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Avocado Oil', isClean: true, isConcern: false },
      { name: 'Cage-Free Eggs', isClean: true, isConcern: false },
      { name: 'Organic Egg Yolks', isClean: true, isConcern: false },
      { name: 'Organic Vinegar', isClean: true, isConcern: false },
      { name: 'Sea Salt', isClean: true, isConcern: false },
      { name: 'Rosemary Extract', isClean: true, isConcern: false },
    ],
    servingSize: '1 tbsp (14g)',
    calories: 90,
    protein: 0,
    fat: 10,
    carbs: 0,
    sugar: 0,
    sodium: 90,
    whyClean: 'No canola oil, no soy oil, no preservatives. Avocado oil base. Whole30 and Paleo approved.',
    price: '$9.49',
    stores: ['whole_foods', 'target', 'kroger'],
    verified: true,
  },
  {
    id: 'nature_path_granola',
    name: 'Hemp Hearts + Dark Chocolate Granola',
    brand: "Nature's Path",
    category: 'cereals',
    emoji: '🌾',
    cleanScore: 72,
    healthScore: 74,
    valueScore: 80,
    badges: ['best_value'],
    confidenceBadge: 'community',
    healthConditionsGoodFor: ['pcos', 'diabetes_t2'],
    allergensPresent: ['tree_nuts'],
    dietCompatible: ['vegan', 'gluten_free'],
    ingredientConcerns: ['natural_flavors'],
    allIngredients: [
      { name: 'Organic Rolled Oats', isClean: true, isConcern: false },
      { name: 'Organic Cane Sugar', isClean: true, isConcern: false, reason: 'Moderate - use in moderation' },
      { name: 'Organic Sunflower Oil', isClean: false, isConcern: true, reason: 'Refined seed oil' },
      { name: 'Hemp Hearts', isClean: true, isConcern: false },
      { name: 'Dark Chocolate Chips', isClean: true, isConcern: false },
      { name: 'Natural Flavors', isClean: false, isConcern: true, reason: 'Ambiguous — source unknown' },
    ],
    servingSize: '1/3 cup (45g)',
    calories: 190,
    protein: 5,
    carbs: 28,
    fat: 8,
    sugar: 9,
    sodium: 70,
    fiber: 3,
    whyClean: 'Organic, non-GMO. Good protein from hemp hearts. Concerns: sunflower oil and natural flavors. Still better than most granolas.',
    price: '$5.99',
    stores: ['whole_foods', 'target', 'kroger', 'safeway'],
    verified: false,
  },
  {
    id: 'epic_jerky',
    name: 'Beef Apple Uncured Bacon Bar',
    brand: 'Epic Provisions',
    category: 'meat',
    emoji: '🥩',
    cleanScore: 79,
    healthScore: 82,
    valueScore: 66,
    badges: ['best_for_you'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['diabetes_t2', 'pcos'],
    allergensPresent: [],
    dietCompatible: ['keto', 'paleo', 'whole30', 'gluten_free', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Grass-Fed Beef', isClean: true, isConcern: false },
      { name: 'Apple', isClean: true, isConcern: false },
      { name: 'Uncured Bacon', isClean: true, isConcern: false },
      { name: 'Sea Salt', isClean: true, isConcern: false },
      { name: 'Celery Juice Powder', isClean: true, isConcern: false },
      { name: 'Spices', isClean: true, isConcern: false },
    ],
    servingSize: '1 bar (43g)',
    calories: 130,
    protein: 10,
    carbs: 7,
    fat: 7,
    sugar: 5,
    sodium: 330,
    fiber: 0,
    whyClean: 'Grass-fed beef. Uncured means no sodium nitrate — natural celery powder instead. Gluten-free. No fillers.',
    price: '$3.49',
    stores: ['whole_foods', 'sprouts', 'target'],
    verified: true,
  },
  {
    id: 'coconut_aminos',
    name: 'Coconut Aminos Soy-Free Seasoning Sauce',
    brand: 'Coconut Secret',
    category: 'condiments',
    emoji: '🧴',
    cleanScore: 91,
    healthScore: 90,
    valueScore: 73,
    badges: ['cleanest', 'best_overall'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['celiac', 'ibs', 'autoimmune' as any],
    allergensPresent: [],
    dietCompatible: ['vegan', 'gluten_free', 'paleo', 'whole30', 'keto', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Organic Coconut Sap', isClean: true, isConcern: false },
      { name: 'Sea Salt', isClean: true, isConcern: false },
    ],
    servingSize: '1 tsp (5ml)',
    calories: 15,
    protein: 0,
    carbs: 4,
    fat: 0,
    sugar: 3,
    sodium: 90,
    whyClean: 'Two ingredients. Soy-free soy sauce alternative. 73% less sodium than soy sauce. USDA Organic. Naturally fermented.',
    price: '$8.99',
    stores: ['whole_foods', 'sprouts'],
    verified: true,
  },
  {
    id: 'bragg_acv',
    name: 'Organic Apple Cider Vinegar',
    brand: 'Bragg',
    category: 'condiments',
    emoji: '🍎',
    cleanScore: 98,
    healthScore: 93,
    valueScore: 92,
    badges: ['cleanest', 'best_value', 'best_overall'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['diabetes_t2', 'pcos', 'high_cholesterol', 'acid_reflux', 'gerd'],
    allergensPresent: [],
    dietCompatible: ['vegan', 'keto', 'paleo', 'whole30', 'gluten_free', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Organic Raw Apple Cider Vinegar', isClean: true, isConcern: false },
      { name: 'The Mother', isClean: true, isConcern: false },
    ],
    servingSize: '1 tbsp (15ml)',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    sugar: 0,
    sodium: 0,
    whyClean: 'One ingredient. Contains "the mother" — live enzymes and probiotics. Raw and unfiltered. Improves insulin sensitivity, gut health, and cholesterol.',
    price: '$6.99',
    stores: ['whole_foods', 'target', 'kroger', 'walmart', 'publix', 'safeway'],
    verified: true,
  },
  {
    id: 'lilys_chocolate',
    name: 'Dark Chocolate Chips, Stevia Sweetened',
    brand: "Lily's",
    category: 'chocolate',
    emoji: '🍪',
    cleanScore: 65,
    healthScore: 76,
    valueScore: 72,
    badges: [],
    confidenceBadge: 'community',
    healthConditionsGoodFor: ['diabetes_t2'],
    allergensPresent: ['dairy'],
    dietCompatible: ['keto', 'gluten_free', 'low_carb'],
    ingredientConcerns: ['sucralose', 'natural_flavors'],
    allIngredients: [
      { name: 'Unsweetened Chocolate', isClean: true, isConcern: false },
      { name: 'Erythritol', isClean: false, isConcern: true, reason: 'Some people experience digestive upset at high amounts' },
      { name: 'Inulin', isClean: true, isConcern: false },
      { name: 'Stevia Extract', isClean: true, isConcern: false },
      { name: 'Vanilla Extract', isClean: true, isConcern: false },
    ],
    servingSize: '60 chips (14g)',
    calories: 80,
    protein: 1,
    carbs: 12,
    fat: 5,
    sugar: 0,
    sodium: 5,
    fiber: 4,
    whyClean: 'Sugar-free. No HFCS, no soy lecithin in this version. Moderate concern: erythritol at high doses may cause GI discomfort.',
    price: '$4.99',
    stores: ['whole_foods', 'target', 'walmart'],
    verified: false,
  },
  {
    id: 'bobs_oats',
    name: 'Organic Extra Thick Rolled Oats',
    brand: "Bob's Red Mill",
    category: 'cereals',
    emoji: '🌾',
    cleanScore: 89,
    healthScore: 85,
    valueScore: 91,
    badges: ['best_value', 'cleanest'],
    confidenceBadge: 'verified',
    healthConditionsGoodFor: ['high_cholesterol', 'diabetes_t2', 'heart_disease', 'pcos'],
    allergensPresent: [],
    dietCompatible: ['vegan', 'vegetarian', 'gluten_free', 'dairy_free'],
    ingredientConcerns: [],
    allIngredients: [
      { name: 'Organic Whole Grain Oats', isClean: true, isConcern: false },
    ],
    servingSize: '1/2 cup dry (40g)',
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    sugar: 1,
    sodium: 0,
    fiber: 4,
    whyClean: 'Single ingredient. Organic. Grown in dedicated gluten-free facility. Beta-glucan fiber reduces LDL cholesterol.',
    price: '$4.29',
    stores: ['whole_foods', 'target', 'kroger', 'walmart', 'publix'],
    verified: true,
  },
];

// ─── Quick-access product subsets ─────────────────────────────────────────────
export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id);
}

export function getProductsByStore(storeId: string): Product[] {
  return PRODUCTS.filter(p => p.stores.includes(storeId));
}

export function getTopCleanProducts(limit = 8): Product[] {
  return [...PRODUCTS].sort((a, b) => b.cleanScore - a.cleanScore).slice(0, limit);
}

export function getProductsForCondition(condition: string, limit = 8): Product[] {
  return PRODUCTS
    .filter(p => p.healthConditionsGoodFor.includes(condition as any))
    .sort((a, b) => b.healthScore - a.healthScore)
    .slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return PRODUCTS.filter(
    p =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
  );
}

// ─── Default user preferences (new user) ─────────────────────────────────────
export const DEFAULT_PREFERENCES: UserPreferences = {
  name: '',
  healthConditions: [],
  allergens: [],
  diets: [],
  ingredientsToAvoid: [],
  customAvoids: [],
  location: 'San Francisco, CA',
  membershipTier: 'free',
  onboardingComplete: false,
};

// ─── Mock shopping lists ──────────────────────────────────────────────────────
export const MOCK_LISTS: ShoppingList[] = [
  {
    id: 'list_1',
    name: 'Weekly Whole Foods Run',
    storeId: 'whole_foods',
    storeName: 'Whole Foods',
    items: [
      { id: 'li_1', product: PRODUCTS[0], quantity: 2, checked: false, addedAt: new Date() },
      { id: 'li_2', product: PRODUCTS[1], quantity: 1, checked: true, addedAt: new Date() },
      { id: 'li_3', product: PRODUCTS[6], quantity: 1, checked: false, addedAt: new Date() },
    ],
    createdAt: new Date(Date.now() - 86400000 * 2),
    updatedAt: new Date(),
    cleanScoreAvg: 89,
  },
  {
    id: 'list_2',
    name: 'Target Quick Picks',
    storeId: 'target',
    storeName: 'Target',
    items: [
      { id: 'li_4', product: PRODUCTS[4], quantity: 3, checked: false, addedAt: new Date() },
      { id: 'li_5', product: PRODUCTS[8], quantity: 1, checked: false, addedAt: new Date() },
    ],
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(),
    cleanScoreAvg: 80,
  },
  {
    id: 'list_3',
    name: 'PCOS-Friendly Pantry',
    items: [
      { id: 'li_6', product: PRODUCTS[0], quantity: 2, checked: false, addedAt: new Date() },
      { id: 'li_7', product: PRODUCTS[11], quantity: 1, checked: false, addedAt: new Date() },
      { id: 'li_8', product: PRODUCTS[13], quantity: 1, checked: false, addedAt: new Date() },
    ],
    createdAt: new Date(Date.now() - 86400000 * 5),
    updatedAt: new Date(Date.now() - 86400000),
    isShared: true,
    sharedWith: ['Dr. Sarah M.'],
    cleanScoreAvg: 91,
  },
];

// ─── Questionnaire metadata ───────────────────────────────────────────────────
export const HEALTH_CONDITION_OPTIONS = [
  { id: 'diabetes_t2',      label: 'Type 2 Diabetes',        emoji: '🩸', description: 'Blood sugar management' },
  { id: 'diabetes_t1',      label: 'Type 1 Diabetes',        emoji: '💉', description: 'Insulin-dependent' },
  { id: 'pcos',             label: 'PCOS / PCOD',            emoji: '🌸', description: 'Hormonal imbalance' },
  { id: 'hypothyroidism',   label: 'Hypothyroidism',         emoji: '🦋', description: 'Underactive thyroid' },
  { id: 'hyperthyroidism',  label: 'Hyperthyroidism',        emoji: '⚡', description: 'Overactive thyroid' },
  { id: 'celiac',           label: 'Celiac Disease',         emoji: '🌾', description: 'Autoimmune gluten' },
  { id: 'ibs',              label: 'IBS',                    emoji: '🫁', description: 'Irritable bowel' },
  { id: 'crohns',           label: "Crohn's / IBD",          emoji: '🔥', description: 'Inflammatory bowel' },
  { id: 'hypertension',     label: 'High Blood Pressure',    emoji: '❤️', description: 'Hypertension' },
  { id: 'high_cholesterol', label: 'High Cholesterol',       emoji: '💛', description: 'Lipid management' },
  { id: 'heart_disease',    label: 'Heart Disease',          emoji: '🫀', description: 'Cardiovascular health' },
  { id: 'gerd',             label: 'GERD / Acid Reflux',     emoji: '🔆', description: 'Digestive health' },
  { id: 'fatty_liver',      label: 'Fatty Liver',            emoji: '🟡', description: 'Liver health' },
  { id: 'anemia',           label: 'Anemia',                 emoji: '🩻', description: 'Iron deficiency' },
  { id: 'eczema',           label: 'Eczema / Psoriasis',     emoji: '🌿', description: 'Skin conditions' },
  { id: 'adhd',             label: 'ADHD',                   emoji: '🧠', description: 'Focus & attention' },
  { id: 'kidney_disease',   label: 'Kidney Disease',         emoji: '🫘', description: 'Renal health' },
  { id: 'osteoporosis',     label: 'Osteoporosis',           emoji: '🦴', description: 'Bone density' },
  { id: 'pregnancy',        label: 'Pregnancy',              emoji: '🤰', description: 'Prenatal nutrition' },
  { id: 'breastfeeding',    label: 'Breastfeeding',          emoji: '🤱', description: 'Postnatal nutrition' },
  { id: 'endometriosis',    label: 'Endometriosis',          emoji: '🌺', description: 'Hormonal condition' },
  { id: 'migraines',        label: 'Migraines',              emoji: '🌩️', description: 'Trigger foods' },
  { id: 'fibromyalgia',     label: 'Fibromyalgia',           emoji: '💜', description: 'Inflammation' },
  { id: 'lupus',            label: 'Lupus / Autoimmune',     emoji: '🛡️', description: 'Autoimmune' },
  { id: 'cancer',           label: 'Cancer (treatment)',     emoji: '🎗️', description: 'In treatment/survivor' },
];

export const ALLERGEN_OPTIONS = [
  { id: 'gluten',      label: 'Gluten / Wheat',  emoji: '🌾' },
  { id: 'dairy',       label: 'Dairy',           emoji: '🥛' },
  { id: 'lactose',     label: 'Lactose',         emoji: '🧀' },
  { id: 'eggs',        label: 'Eggs',            emoji: '🥚' },
  { id: 'peanuts',     label: 'Peanuts',         emoji: '🥜' },
  { id: 'tree_nuts',   label: 'Tree Nuts',       emoji: '🌰' },
  { id: 'soy',         label: 'Soy',             emoji: '🫘' },
  { id: 'fish',        label: 'Fish',            emoji: '🐟' },
  { id: 'shellfish',   label: 'Shellfish',       emoji: '🦐' },
  { id: 'sesame',      label: 'Sesame',          emoji: '⚪' },
  { id: 'corn',        label: 'Corn',            emoji: '🌽' },
  { id: 'nightshades', label: 'Nightshades',     emoji: '🍅' },
  { id: 'sulfites',    label: 'Sulfites',        emoji: '🍷' },
  { id: 'fructose',    label: 'Fructose',        emoji: '🍬' },
];

export const DIET_OPTIONS = [
  { id: 'vegan',           label: 'Vegan',              emoji: '🌱' },
  { id: 'vegetarian',      label: 'Vegetarian',         emoji: '🥗' },
  { id: 'pescatarian',     label: 'Pescatarian',        emoji: '🐠' },
  { id: 'keto',            label: 'Keto',               emoji: '🥑' },
  { id: 'low_carb',        label: 'Low-Carb',           emoji: '🥩' },
  { id: 'paleo',           label: 'Paleo',              emoji: '🦴' },
  { id: 'carnivore',       label: 'Carnivore',          emoji: '🥩' },
  { id: 'gluten_free',     label: 'Gluten-Free',        emoji: '🚫' },
  { id: 'dairy_free',      label: 'Dairy-Free',         emoji: '🥛' },
  { id: 'whole30',         label: 'Whole30',            emoji: '🔄' },
  { id: 'mediterranean',   label: 'Mediterranean',      emoji: '🫒' },
  { id: 'low_fodmap',      label: 'Low-FODMAP',         emoji: '🔬' },
  { id: 'anti_inflammatory','label': 'Anti-Inflammatory', emoji: '💊' },
  { id: 'halal',           label: 'Halal',              emoji: '☪️' },
  { id: 'kosher',          label: 'Kosher',             emoji: '✡️' },
  { id: 'jain',            label: 'Jain',               emoji: '🕊️' },
  { id: 'raw_vegan',       label: 'Raw Vegan',          emoji: '🥬' },
];

export const INGREDIENT_AVOID_OPTIONS = [
  { id: 'hfcs',              label: 'High Fructose Corn Syrup', emoji: '🍬', category: 'Sweeteners' },
  { id: 'aspartame',         label: 'Aspartame',               emoji: '🧪', category: 'Sweeteners' },
  { id: 'sucralose',         label: 'Sucralose (Splenda)',      emoji: '🧪', category: 'Sweeteners' },
  { id: 'saccharin',         label: 'Saccharin',               emoji: '🧪', category: 'Sweeteners' },
  { id: 'acesulfame_k',      label: 'Acesulfame K (Ace-K)',    emoji: '🧪', category: 'Sweeteners' },
  { id: 'artificial_dyes',   label: 'Artificial Food Dyes',    emoji: '🎨', category: 'Additives' },
  { id: 'red40',             label: 'Red 40',                  emoji: '🔴', category: 'Additives' },
  { id: 'yellow5',           label: 'Yellow 5',                emoji: '🟡', category: 'Additives' },
  { id: 'sodium_nitrate',    label: 'Sodium Nitrate/Nitrite',  emoji: '⚠️', category: 'Preservatives' },
  { id: 'bha',               label: 'BHA / BHT',              emoji: '⚗️', category: 'Preservatives' },
  { id: 'tbhq',              label: 'TBHQ',                    emoji: '⚗️', category: 'Preservatives' },
  { id: 'carrageenan',       label: 'Carrageenan',             emoji: '🌊', category: 'Additives' },
  { id: 'msg',               label: 'MSG',                     emoji: '🍜', category: 'Flavor Enhancers' },
  { id: 'trans_fats',        label: 'Trans Fats',              emoji: '🚫', category: 'Fats' },
  { id: 'seed_oils',         label: 'Seed Oils (all)',         emoji: '🛢️', category: 'Fats' },
  { id: 'canola_oil',        label: 'Canola Oil',              emoji: '🌱', category: 'Fats' },
  { id: 'soybean_oil',       label: 'Soybean Oil',             emoji: '🫘', category: 'Fats' },
  { id: 'maltodextrin',      label: 'Maltodextrin',            emoji: '🍚', category: 'Fillers' },
  { id: 'titanium_dioxide',  label: 'Titanium Dioxide',        emoji: '⬜', category: 'Additives' },
  { id: 'carboxymethylcellulose', label: 'CMC / Cellulose Gum', emoji: '🔬', category: 'Additives' },
  { id: 'polysorbate_80',    label: 'Polysorbate 80',          emoji: '🔬', category: 'Emulsifiers' },
  { id: 'natural_flavors',   label: '"Natural Flavors"',       emoji: '❓', category: 'Flavor Enhancers' },
  { id: 'sodium_benzoate',   label: 'Sodium Benzoate',         emoji: '⚠️', category: 'Preservatives' },
  { id: 'potassium_bromate', label: 'Potassium Bromate',       emoji: '⚠️', category: 'Additives' },
  { id: 'brominated_veg_oil','label': 'Brominated Vegetable Oil', emoji: '🛢️', category: 'Additives' },
  { id: 'caramel_color',     label: 'Caramel Color (Class IV)', emoji: '🍮', category: 'Additives' },
  { id: 'silicon_dioxide',   label: 'Silicon Dioxide',         emoji: '🔬', category: 'Anti-caking' },
  { id: 'propyl_gallate',    label: 'Propyl Gallate',          emoji: '⚗️', category: 'Preservatives' },
];
